### ISSUE TITLE
Reading Views --- word mouseover

### ISSUE THREAD

**Issue by RJP43** [PPH3/Eldritch#15]
**Task List to get Reading Views with Word Mouseovers**

- [x] XSLT identity transform that maps code from fullList_syn.xml onto the three text XMLs

- [ ] XSLT XML to HTML transformation to implement styling and javaScript on the new word markup

- [ ] edit CSS to prep for show/hide: http://digitalmitford.org/mitfordletter.css and think about CSS color coding for religious, scientific, etc words

- [ ] Use classList toggle() for JavaScript to show/hide the note for each word (`<span class="note">`)

**Comment by RJP43** [comment]
**New XML Format**

`<w>ancient<w>` **becomes** `<w synCount="4" type="other">ancient</><note>List of synsets and other info from fullList_syn.xml goes in here</note>`

**New HTML Format**

`<span title="4" class="other">ancient</><note>List of synsets and other info from fullList_syn.xml goes in here</note>`
