### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by PPH3** [PPH3/Eldritch#2]
Group meeting tomorrow in our normal class room at 12:30 pm

**Comment by mjb232** [comment]
# Tasks Completed at Meeting
1. determine source text
2. push plain text files of source texts to repo
3. determine site name
4. touch base with project team on goals of project and each member's git repo status

# Tasks for Next Meeting
- [ ] Determining Thesis statement/research question @PPH3 
- [ ] Document analysis of Mountains of Madness @etj27 
- [ ] Document analysis of Call of Cthulu and Shadows over Innsmouth  @mjb232

**Comment by mjb232** [comment]
Next meeting will be Tuesday, Oct. 4, at 12:30 in our classroom (or neighboring McKenna classroom).

**Comment by ebeshero** [comment]
@PPH3 @mjb232 @etj27 How long is your meeting running today? I've got a faculty meeting over the lunch hour, which will likely be ending around 12:45 or 1pm, but would like to join you this round to share some markup strategies/suggestions... I'll write more about that on Patrick's new issue on Research Questions.

**Comment by mjb232** [comment]
@RJP43  @ebeshero Sorry for the late update! But here is what we covered in out meeting:

We had a long discussion on whether or not we want to use TEI. The benefits of using TEI would make our mark-up more professional, flexible, and increase the longevity of the documents. The down side is that the TEI mark up might be to restricting. The Tei tags might not accommodate the mark-up of Eldritch gods, Lovecraft's fictional language, and the "weird" vocabulary Lovecraft tends to use. 

We also discussed our research question and thesis statement. We want to focus on the seemingly "weird" vocabulary that Lovecraft utilizes in his texts to give them an archaic feel. Along with this we still want to highlight and explore the origins and inspirations behind the Eldritch pantheon. 

There was talk of adding a fourth text: The Case of Charles Dextar Ward. This text has a well spring of content, but the issue is its length. These texts will require some form of close reading, and we already have a lot to read through. We concluded that we would keep the text in mind and would work on it if we had time after we finished with the first three. The hope here is that once we discover patterns withing the first three texts, we can then use those to mark up Charles Ward from a distance. 

We concluded that before the next meeting, either Tuesday the 11th or Thrusday 13th, we would try and accomplish the following:
1- Pat and I will begin marking up our shadows.txt document and our call.txt document. We will not only be doing structural and contextual mark-up, but also a close read with the intent of marking up any "weird"  vocabulary. At this early point in the project we are being generous with our "weird" vocabulary and will condense our list of "weird" words later with further research. 

2-Evan will be studying the TEI with the hopes of finding a form of it in which we can most freely mark-up our texts. Once Pat and I are done working with our texts we will discuss the plausibility of using  TEI after looking at what tags we used. If we decide we want to use TEI we will use XSLT to convert our current mark up to the TEI, if we choose not to we will establish a consistent mark-up method, which we will use on the large text of At the Mountains of Madness.
